import { Handlers } from "$fresh/server.ts";
import { slug } from "https://deno.land/x/slug@v1.1.0/mod.ts";

type TopicRequest = {
  name: string;
};

type Topic = {
  id: string; // TODO: This should be autogenerated uuid.
  name: string;
  slug: string;
};

const kv = await Deno.openKv();

export const handler: Handlers<Topic | null> = {
  async GET(_req, _ctx) {
    const topics = [];

    for await (const res of kv.list({ prefix: ["topics"] })) {
      topics.push(res.value);
    }

    return new Response(JSON.stringify(topics));
  },

  async POST(req, _ctx) {
    const topicRequest = (await req.json()) as TopicRequest;

    // TODO: Add validation with Zog
    // TODO: Implement access token which does not change on signin.

    const topic: Topic = {
      id: self.crypto.randomUUID(),
      name: topicRequest.name,
      slug: slug(topicRequest.name),
    };

    const topicKey = ["topics", topic.id];

    const ok = await kv.atomic().set(topicKey, topic).commit();

    if (!ok) throw new Error("Something went wrong.");

    return new Response(JSON.stringify(topic));
  },
};
