name: Release

on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*-cli"]

jobs:
  release-linux:
    name: Release all
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task --cwd ./cli compile:all"

      - name: Create release and upload assets (private)
        run: 'gh release create ${{ github.ref_name }} ./cli/dist/*'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release and upload assets (public)
        run: 'gh release create ${{ github.ref_name }} ./cli/dist/* -R https://github.com/govisit/DownTimer-docs'
        env:
          GH_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}

