name: Release

on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*-cli"]

jobs:
  release-linux:
    name: Release all
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task --cwd ./cli compile:all"

      - name: Compress assets
        run: |
          tar -czvf ./cli/dist/dt-x86_64-unknown-linux-gnu.tar.gz ./cli/dist/dt-x86_64-unknown-linux-gnu 
          tar -czvf ./cli/dist/dt-x86_64-pc-windows-msvc.tar.gz ./cli/dist/dt-x86_64-pc-windows-msvc.exe
          tar -czvf ./cli/dist/dt-x86_64-apple-darwin.tar.gz ./cli/dist/dt-x86_64-apple-darwin.dmg 
          tar -czvf ./cli/dist/dt-aarch64-apple-darwin.tar.gz ./cli/dist/dt-aarch64-apple-darwin.dmg

      - name: Create release and upload assets (private)
        run: 'gh release create ${{ github.ref_name }} ./cli/dist/*.tar.gz'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release and upload assets (public)
        run: 'gh release create ${{ github.ref_name }} ./cli/dist/*.tar.gz -R https://github.com/govisit/DownTimer-docs'
        env:
          GH_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}

