// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $download from "./routes/download.tsx";
import * as $features from "./routes/features.tsx";
import * as $index from "./routes/index.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Shell from "./islands/Shell.tsx";
import * as $ShellLine from "./islands/ShellLine.tsx";
import * as $ShellPrompt from "./islands/ShellPrompt.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/download.tsx": $download,
    "./routes/features.tsx": $features,
    "./routes/index.tsx": $index,
    "./routes/privacy.tsx": $privacy,
  },
  islands: {
    "./islands/Header.tsx": $Header,
    "./islands/Shell.tsx": $Shell,
    "./islands/ShellLine.tsx": $ShellLine,
    "./islands/ShellPrompt.tsx": $ShellPrompt,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
